### ISSUE TITLE
Find a concise (maybe creative?) name for the project

### ISSUE THREAD

**Issue by chenlijun99** [plant-a-seed/management#13]
In a single GitHub organization, repositories must not have the same name, so to avoid potential problem with future PaS software projects (maybe vertical farming?) we should find a prefix for the names of the repositories of irrigation system.

"Irrigation system" is also long to type and clutters the code. In many cases we'll need a short project namespace in the source code. In C people commonly prefix every global symbol (i.e. not translation unit specific, i.e. not declared with `static`) with some prefix to avoid name collision. In C++ we have `namespace` but still it usually is a short namespace, not too long. Java's module system also encourages some kind of hierarchal structure of packages (e.g. `tum.pas.${this project}.MyClass`) and also there having "irrigation_system" in the place of `${this_project}` seems to long. Etc.

We could come up with a good project name and, if it's long, also come up with a short variant ideally with <=5 characters that we'll use for namespace purposes. Of course, keeping "Irrigation system" is also fine, then the short variant could be e.g. `is` or `irsys`.

**Comment by euberdeveloper** [comment]
I like the idea, but not the name, just a shortcut for "irrigation system" is boring. 

Soooooo....  **let's propose other names on the comments!**

We are going to do a poll by the next meeting to choose one

**Comment by Valleygold** [comment]
Watering 😂

**Comment by turnipseason** [comment]
I think `irsys` is really good, but I also thought of two acronyms:

1. `tipse` for "Telemetry and Irrigation for Plant a SEed". 
Could be pronounces as 'tipsy' for maximum fun, I suppose. 
2. `terre` for "TElemetry and iRRigation Efforts/tEam". 
If I remember correctly that's French for "Earth", so it's also thematically appropriate lol.

**Comment by chenlijun99** [comment]
I like `terre`. Also in Italian `terra` means "Earth" and also means "land". `terre` would be plular version, so "lands".

**Comment by euberdeveloper** [comment]
In french it'd be Terres the plural, but lands makes sense because it handles more beds

**Comment by euberdeveloper** [comment]
TODO: add a poll on telegram
