### ISSUE TITLE
Understand which were the problems with using eduroam WiFi

### ISSUE THREAD

**Issue by chenlijun99** [plant-a-seed/management#2]
Things to consider:

1. Which (whose?) eduroam credentials to use for the deployed system?
2. Will the eduroam network be available in every deployment site? If not, we'll need to fallback to cellular network (i.e. use SIM).
3. ✅ ESP32 supports WiFi EAP authentication (see https://docs.espressif.com/projects/esp-idf/en/v5.0.1/esp32/api-guides/wifi.html#wpa2-enterprise). So yeah, we can directly connect each ESP32 to eduroam.
    3.1. Storing eduroam credentials on each ESP32 is undesirable. Why? Is that a security issue? What's our security model? Or is that a burecracy issue related to item 1?
    3.2. Anyway, we could have a single ESP32 where we store the eduroam credentials. That special ESP32 can work as eduroam forwarder. See #3 . That's certainly very cheap.

**Comment by euberdeveloper** [comment]
3.1 I wouldn't put my credentials in a device that anyone can take

**Comment by euberdeveloper** [comment]
3.2 seems better

**Comment by euberdeveloper** [comment]
Ok, so the idea now would be:
1. buy two ESP 32 and use one to setup this forwarder solution
2. look for a professional hotspot and buy it

I close this issue because of #3
